services:
  db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db-data:
